language: python

python: 3.7-dev
services: mongodb

env: 
 - DJANGO=2.1.7

before_install:
  - export DJANGO_SETTINGS_MODULE=public_python.settings  
  - export PIP_USE_MIRRORS=true
  - export PYTHONPATH="/usr/local/lib/python3.7/dist-packages"
  
install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet
  - pip install codecov

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
  - coverage run tests.py
  
after_success:
 - codecov
